Added release condition

diff --git a/.buildkite/bin/release b/.buildkite/bin/release
--- a/.buildkite/bin/release
+++ b/.buildkite/bin/release
@@ -5,27 +5,32 @@ set -eo pipefail
 latest="true"
 imageRepo="${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}"
 
-if [ -z "${TERRAFORM_VERSION}" ]; then
-    export TERRAFORM_VERSION=$(buildkite-agent meta-data get terraform-version)
+if [ "${BUILDKITE}" == "true" ]; then
+    if [ -z "${TERRAFORM_VERSION}" ]; then
+        export TERRAFORM_VERSION=$(buildkite-agent meta-data get terraform-version)
+    else
+        latest="false"
+    fi
+
+    minor=$TERRAFORM_VERSION
+    major=${TERRAFORM_VERSION%.*}
+
+    docker pull ${imageRepo}:${minor}-beta
+
+    echo "+++ :docker: Tag ${imageRepo}:${minor}-beta => ${imageRepo}:${minor}"
+    docker tag ${imageRepo}:${minor}-beta ${imageRepo}:${minor}
+    docker push ${imageRepo}:${minor}
+
+    if [ "${latest}" == "true" ]; then
+        echo "+++ :docker: Tag ${imageRepo}:${minor}-beta => ${imageRepo}:${major}"
+        docker tag ${imageRepo}:${minor}-beta ${imageRepo}:${major}
+        docker push ${imageRepo}:${major}
+
+        echo "+++ :docker: Tag ${imageRepo}:${minor}-beta => ${imageRepo}:latest"
+        docker tag ${imageRepo}:${minor}-beta ${imageRepo}:latest
+        docker push ${imageRepo}:latest
+    fi
 else
-    latest="false"
-fi
-
-minor=$TERRAFORM_VERSION
-major=${TERRAFORM_VERSION%.*}
-
-docker pull ${imageRepo}:${minor}-beta
-
-echo "+++ :docker: Tag ${imageRepo}:${minor}-beta => ${imageRepo}:${minor}"
-docker tag ${imageRepo}:${minor}-beta ${imageRepo}:${minor}
-docker push ${imageRepo}:${minor}
-
-if [ "${latest}" == "true" ]; then
-    echo "+++ :docker: Tag ${imageRepo}:${minor}-beta => ${imageRepo}:${major}"
-    docker tag ${imageRepo}:${minor}-beta ${imageRepo}:${major}
-    docker push ${imageRepo}:${major}
-
-    echo "+++ :docker: Tag ${imageRepo}:${minor}-beta => ${imageRepo}:latest"
-    docker tag ${imageRepo}:${minor}-beta ${imageRepo}:latest
-    docker push ${imageRepo}:latest
+    echo "ERROR   Docker image cannot be released outside of the Buildkite pipeline!"
+    exit 1
 fi
